/** Fictional preview copy. Replace with approved client quotes before presenting as testimonials. */
export type Review = { id: string; name: string; initials: string; role: string; location: string; subject: string; quote: string };
export const SAMPLE_REVIEWS: Review[] = [
  { id: "01", name: "Amelia R.", initials: "AR", role: "Interior designer", location: "London, UK", subject: "The finishing details", quote: "The brass finish was exactly what we were looking for — warm, but not too shiny. We ordered the sample first and came back for the full set of lamps." },
  { id: "02", name: "Marco B.", initials: "MB", role: "Boutique owner", location: "Milan, Italy", subject: "Better in the hand", quote: "The vases have a lovely weight to them. You can see the handwork up close, which is what our customers tend to notice first. Beautifully packed, too." },
  { id: "03", name: "Sarah K.", initials: "SK", role: "Hospitality buyer", location: "Dubai, UAE", subject: "A thoughtful process", quote: "We needed a slightly different finish for a restaurant project. The team sent close-up photos before we approved it, and the pieces arrived just as shown." },
  { id: "04", name: "Daniel W.", initials: "DW", role: "Design studio founder", location: "New York, USA", subject: "Worth the sample", quote: "It is difficult to judge metal finishes on a screen. Having a sample made the decision easy. The final candle stands sit beautifully with the client's existing pieces." },
  { id: "05", name: "Clara M.", initials: "CM", role: "Residential designer", location: "Barcelona, Spain", subject: "Quiet statement pieces", quote: "We used two of the bowls on a very simple console. They add just enough texture without taking over the room. The proportions are especially good." },
  { id: "06", name: "Mei L.", initials: "ML", role: "Retail buyer", location: "Singapore", subject: "Care in every parcel", quote: "Our first order was quite small, but the communication was still attentive. Each piece was wrapped separately, and the care notes were a helpful touch." },
  { id: "07", name: "James O.", initials: "JO", role: "Project stylist", location: "Nairobi, Kenya", subject: "A good working rhythm", quote: "We had a few questions about dimensions before ordering. Getting clear answers made the process straightforward. The trays were a lovely addition to the project." },
  { id: "08", name: "Elif D.", initials: "ED", role: "Interior architect", location: "Istanbul, Türkiye", subject: "Texture, not perfection", quote: "I like that the surfaces are not completely uniform. There is a softness to the hammered finish that you simply do not get with a factory-made piece." },
  { id: "09", name: "Sophie A.", initials: "SA", role: "Private client", location: "Zürich, Switzerland", subject: "Made to keep", quote: "The lamp is now the first thing we switch on in the evening. The colour of the brass is softer than I expected, in the nicest possible way." },
  { id: "10", name: "Oliver H.", initials: "OH", role: "Trade buyer", location: "Manchester, UK", subject: "An easy second order", quote: "We started with a few pieces to see the quality. The next order was much easier because we already knew the finish and scale. A very useful collection for our projects." },
];
